name: "Gitbook Action Build"
on:
  push:
    branches:
      - master # trigger branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
      - name: Gitbook Action # https://github.com/ZanderZhao/gitbook-action/releases
        uses: bgoonz/gitbook-action@master # -> or ZanderZhao/gitbook-action@master.  If not use master click above, use latest please
        with: 
          token: ${{ secrets.PERSONAL_TOKEN }}
          time_zone: Asia/Shanghai   # set time zone
          publish_nojekyll: true
          source_dir: source         # clone from source
          source_edit_time: true     # source time
          publish_commit_message: ${{ github.event.head_commit.message }}  # use last commit message